# Generated by Django 5.0.2 on 2024-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compEng', '0002_alter_facultyuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=10)),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
                ('mark3', models.IntegerField()),
            ],
        ),
    ]
